services:
  video-downloader:
    image: chanki87/video-downloader:latest
    container_name: video-downloader
    ports:
      - "5001:5000"
    volumes:
      - downloads:/app/downloads
      - /mnt/oracle/video:/final
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FINAL_DIR=/final

volumes:
  downloads:
